//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MFSoft_Base_EdaltecEntities : DbContext
    {
        public MFSoft_Base_EdaltecEntities()
            : base("name=MFSoft_Base_EdaltecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pub_Usuarios> Pub_Usuarios { get; set; }
        public virtual DbSet<Tbl_AccesoOpciones> Tbl_AccesoOpciones { get; set; }
        public virtual DbSet<tbl_Aceesos> tbl_Aceesos { get; set; }
        public virtual DbSet<tbl_Aceesos_Evento> tbl_Aceesos_Evento { get; set; }
        public virtual DbSet<tbl_Definicion_Opciones> tbl_Definicion_Opciones { get; set; }
        public virtual DbSet<tbl_w_OT_Cab> tbl_w_OT_Cab { get; set; }
        public virtual DbSet<Prj_MPrv_LiquidacionTrab> Prj_MPrv_LiquidacionTrab { get; set; }
        public virtual DbSet<tbl_w_OT_Det> tbl_w_OT_Det { get; set; }
        public virtual DbSet<tbl_w_OrdenTrabajo_CAB> tbl_w_OrdenTrabajo_CAB { get; set; }
        public virtual DbSet<tbl_w_Cliente> tbl_w_Cliente { get; set; }
        public virtual DbSet<tbl_w_Periodo> tbl_w_Periodo { get; set; }
        public virtual DbSet<tbl_w_Servicio> tbl_w_Servicio { get; set; }
        public virtual DbSet<tbl_w_TipoReparacion> tbl_w_TipoReparacion { get; set; }
        public virtual DbSet<tbl_w_TiposObras> tbl_w_TiposObras { get; set; }
        public virtual DbSet<Pub_Estados> Pub_Estados { get; set; }
        public virtual DbSet<tbl_w_Cliente_TipoReparacion> tbl_w_Cliente_TipoReparacion { get; set; }
        public virtual DbSet<tbl_w_Carroceria_Vehiculo> tbl_w_Carroceria_Vehiculo { get; set; }
        public virtual DbSet<tbl_w_Categoria_Vehiculo> tbl_w_Categoria_Vehiculo { get; set; }
        public virtual DbSet<tbl_w_Tipo_Vehiculo> tbl_w_Tipo_Vehiculo { get; set; }
        public virtual DbSet<tbl_w_Vehiculo> tbl_w_Vehiculo { get; set; }
        public virtual DbSet<tbl_w_OrdenTrabajo_Programacion> tbl_w_OrdenTrabajo_Programacion { get; set; }
        public virtual DbSet<tbl_w_Contrato> tbl_w_Contrato { get; set; }
        public virtual DbSet<tbl_w_Marca_Vehiculo> tbl_w_Marca_Vehiculo { get; set; }
    }
}
