//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prj_MPrv_LiquidacionTrab
    {
        public int id_OT { get; set; }
        public string PMPr_LiqT_Codigo { get; set; }
        public string PMPr_LiqT_OT { get; set; }
        public string PMPr_SecC_Codigo { get; set; }
        public string Ges_Ctto_NroContrato { get; set; }
        public Nullable<int> id_Cliente { get; set; }
        public string PMPr_Ceco_Codigo { get; set; }
        public string PMPr_LiqT_SIE { get; set; }
        public string PMPr_LiqT_Sed { get; set; }
        public string PMPr_LiqT_OT_Relac { get; set; }
        public string PMPr_LiqT_OT_ISCO { get; set; }
        public string PMPr_LiqT_Descripcion { get; set; }
        public string PMPr_LiqT_Alimentador { get; set; }
        public string PMPr_LiqT_Circuito { get; set; }
        public string PMPr_LiqT_DGruZona { get; set; }
        public string PMPr_LiqT_DGruProceso { get; set; }
        public Nullable<int> PMPr_LiqT_Semana { get; set; }
        public string PMPr_LiqT_DGruActividad { get; set; }
        public string PMPr_LiqT_DGruSubActividad { get; set; }
        public string PMPr_Resp_Codigo { get; set; }
        public string Ges_Empl_DNI { get; set; }
        public Nullable<int> id_Distrito { get; set; }
        public Nullable<System.DateTime> PAlu_Orde_FechaRegistro { get; set; }
        public Nullable<System.DateTime> PMPr_LiqT_Inicio { get; set; }
        public Nullable<System.DateTime> PMPr_LiqT_Termino { get; set; }
        public Nullable<System.DateTime> PAlu_Orde_FechaEjecucion { get; set; }
        public string PAlu_Orde_FechaEjecucionHora { get; set; }
        public Nullable<System.DateTime> PAlu_Orde_FechaLiquidacion { get; set; }
        public string PMPr_LiqT_Hora_Inicio_Real { get; set; }
        public string PMPr_LiqT_Hora_Termino_Real { get; set; }
        public string PMPr_LiqT_Hora_Total_Real { get; set; }
        public string PMPr_LiqT_Observaciones { get; set; }
        public string PMPr_EstadoISCO_Descripcion { get; set; }
        public string Pub_Esta_Codigo { get; set; }
        public string PAlu_Orde_UsuCrea { get; set; }
        public Nullable<System.DateTime> PAlu_Orde_FecCrea { get; set; }
        public string PAlu_Orde_UsuModi { get; set; }
        public Nullable<System.DateTime> PAlu_Orde_FecModi { get; set; }
    }
}
