//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pub_Estados
    {
        public string Pub_Esta_Codigo { get; set; }
        public string Pub_Esta_Nombre { get; set; }
        public string Pub_Esta_UsuCrea { get; set; }
        public Nullable<System.DateTime> Pub_Esta_FecCrea { get; set; }
        public string Pub_Esta_UsuModi { get; set; }
        public Nullable<System.DateTime> Pub_Esta_FecModi { get; set; }
        public string Pub_Esta_Tipo { get; set; }
        public int Pub_Esta_Identidad { get; set; }
        public string Pub_Modu_Codigo { get; set; }
        public Nullable<int> Pub_Esta_Orden { get; set; }
        public string Pub_Esta_Tipo_Descripcion { get; set; }
    }
}
