//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_w_OT_Det
    {
        public int id_Ot_Det { get; set; }
        public Nullable<int> id_Ot { get; set; }
        public Nullable<int> id_TipoTrabajo { get; set; }
        public Nullable<int> item { get; set; }
        public Nullable<int> id_Area { get; set; }
        public Nullable<int> id_supervisorContratista { get; set; }
        public Nullable<System.DateTime> fechaInspeccion { get; set; }
        public string codigoEstructura { get; set; }
        public string subTipoEstructura { get; set; }
        public string tipoArmado { get; set; }
        public string posteInicioDMS { get; set; }
        public string posteFinalDMS { get; set; }
        public string MtMc { get; set; }
        public string sedCercana { get; set; }
        public string alimentador { get; set; }
        public string circuito { get; set; }
        public string tipoAnomalia { get; set; }
        public Nullable<int> id_Anomalia { get; set; }
        public string codigo_Anomalia { get; set; }
        public string categoria_Anomalia { get; set; }
        public Nullable<int> id_SubFamilia_Anomalia { get; set; }
        public string Alcance_Anomalia { get; set; }
        public string criticidad_Anomalia { get; set; }
        public Nullable<int> id_ObservacionInspeccion { get; set; }
        public Nullable<int> id_Distrito { get; set; }
        public Nullable<int> id_Zona { get; set; }
        public Nullable<int> id_ResponsableEnel { get; set; }
        public string tamanioPoste { get; set; }
        public Nullable<int> id_MatPST { get; set; }
        public string accesoVehiculo { get; set; }
        public Nullable<int> id_superficie { get; set; }
        public string redesTeleco { get; set; }
        public string equipoTeleco { get; set; }
        public string zocalo { get; set; }
        public string mantCalScb { get; set; }
        public string regisCarg { get; set; }
        public string medPozoTierra { get; set; }
        public string inspSCB { get; set; }
        public string termovision { get; set; }
        public string potenciaTransformador { get; set; }
        public string Marca { get; set; }
        public string Kardex { get; set; }
        public string Mt { get; set; }
        public string BT { get; set; }
        public string horaToma { get; set; }
        public string TernaSCC { get; set; }
        public string seccionCable { get; set; }
        public string tipoCable { get; set; }
        public string r { get; set; }
        public string s { get; set; }
        public string t { get; set; }
        public string tablero { get; set; }
        public string llaveBT { get; set; }
        public string terna { get; set; }
        public string seccion { get; set; }
        public string material { get; set; }
        public string tipo { get; set; }
        public string fusible { get; set; }
        public string Cap { get; set; }
        public string r2 { get; set; }
        public string s2 { get; set; }
        public string t2 { get; set; }
        public string Sub_Cod_PFPSRC { get; set; }
        public string Sub_Tipo_Estruc { get; set; }
        public string TipoTablero { get; set; }
        public string set_DE { get; set; }
        public string codigo_DE { get; set; }
        public string Deficiencia_Enel { get; set; }
        public string Observacion_Inspeccion { get; set; }
        public Nullable<System.DateTime> MantCali_Fecha { get; set; }
        public string MantCali_CantidadLLave { get; set; }
        public string MantCali_Material { get; set; }
        public string codigo_id { get; set; }
        public string subFamilia_anomalia { get; set; }
    }
}
