//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_w_OrdenTrabajo_CAB
    {
        public int id_OrdenTrabajo { get; set; }
        public Nullable<int> id_Servicio { get; set; }
        public Nullable<System.DateTime> fechaCorreo_OrdenTrabajo { get; set; }
        public string extension { get; set; }
        public Nullable<System.DateTime> fechaElectrica_OrdenTrabajo { get; set; }
        public Nullable<System.DateTime> fechaAsignada_OrdenTrabajo { get; set; }
        public Nullable<int> id_TipoTrabajo { get; set; }
        public string numero_OrdenTrabajo { get; set; }
        public string nroCliente_OrdenTrabajo { get; set; }
        public Nullable<int> id_Distrito { get; set; }
        public string direccion_OrdenTrabajo { get; set; }
        public string nroSED { get; set; }
        public string cliente_OrdenTrabajo { get; set; }
        public string cxr_OrdenTrabajo { get; set; }
        public Nullable<System.DateTime> fechaProgramada_OrdenTrabajo { get; set; }
        public Nullable<int> id_Supervisor { get; set; }
        public Nullable<int> id_Supervisor2 { get; set; }
        public Nullable<System.DateTime> fechaAsigndaCampo_OrdenTrabajo { get; set; }
        public string supervisorContratista { get; set; }
        public Nullable<decimal> cantDesm { get; set; }
        public Nullable<System.DateTime> fechaElimDes_OrdenTrabajo { get; set; }
        public Nullable<System.DateTime> fechaEjecutado_OrdenTrabajo { get; set; }
        public string personal_OrdenTrabajo { get; set; }
        public string cemento_OrdenTrabajo { get; set; }
        public string logistica_OrdenTrabajo { get; set; }
        public string tiempoGrabEfect_OrdenTrabajo { get; set; }
        public string tiempoGrabDesest_OrdenTrabajo { get; set; }
        public string unidad_OrdenTrabajo { get; set; }
        public string gastoGenerales_OrdenTrabajo { get; set; }
        public string salida_OrdenTrabajo { get; set; }
        public string llegada_OrdenTrabajo { get; set; }
        public string km_OrdenTrabajo { get; set; }
        public string id_Estado { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    }
}
