
export const registroOtTypes =  {  
    
    inicializarTabs : 'Inicializar Tabs',
    clientes : 'combo Clientes OT',
    tipoTrabajos : 'combo tipo de Trabajos OT',
    inspeccionados : 'listado Inspeccionados OT',
    listaOTs : 'listado OT Cabecera',
    set_formParamsTab1 : 'Actualizar form params',
    idOrdenTrabajo : 'idOrdenTrabajo_global ',
    areas : 'combo areas',
    distritos : 'combo distritos',
    supervisores : 'combo supervisores',
    tiposReparacion : 'combo tiposReparacion',
    estados : 'combo estados',
    set_formParamsOcurrenciaInicial : 'Actualizar form Ocurrencias',
    listaOcurrencias : 'listado ocurrencias OT',
    listaTiposReparacionMontos : 'listado Tipos Reparacion Montos',
    listaTiposReparacionMultipleOT  : 'listado tipos reparacion Multiple',
    set_tiposReparacionesMultiple : 'Actualizar check tipoReparacion',
    set_terminoCargaArchivo : 'Indica que un archivo termino de cargar',
    listaArchivosEvidencias : 'listado Archivos Cargados Evidencias',
    anulandoArchivoEvidencia: 'Anular Archivo Cargados Evidencia',
    set_formParamsMetrados: 'Actualizar form Metrados',
    listMetrados :  'listado de metrados',
    anulandoMetrado: 'Anular Metrado',
    listaFotosTab4 : 'listado Fotos Tab 4',
    eliminarFotoTab4: 'Eliminar Foto tab 4',
}